/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.editor.operadores;

import java.util.Collection;
import org.editor.operadores.api.Calcula;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.editor.operadores//editor//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "editorTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "org.editor.operadores.editorTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_editorAction",
        preferredID = "editorTopComponent"
)
@Messages({
    "CTL_editorAction=editor",
    "CTL_editorTopComponent=editor Window",
    "HINT_editorTopComponent=This is a editor window"
})

public final class editorTopComponent extends TopComponent {
    private InstanceContent content;
    public editorTopComponent() {
        initComponents();
        setName(Bundle.CTL_editorTopComponent());
        setToolTipText(Bundle.HINT_editorTopComponent());
        content = new InstanceContent();
        associateLookup(new AbstractLookup(content));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        op1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        op2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRes = new javax.swing.JTextArea();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(editorTopComponent.class, "editorTopComponent.jLabel1.text")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(50, 22, 57, 14);

        op1.setText(org.openide.util.NbBundle.getMessage(editorTopComponent.class, "editorTopComponent.op1.text")); // NOI18N
        add(op1);
        op1.setBounds(48, 54, 130, 20);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(editorTopComponent.class, "editorTopComponent.jLabel2.text")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(232, 22, 57, 14);

        op2.setText(org.openide.util.NbBundle.getMessage(editorTopComponent.class, "editorTopComponent.op2.text")); // NOI18N
        add(op2);
        op2.setBounds(230, 54, 130, 20);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(editorTopComponent.class, "editorTopComponent.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(289, 111, 71, 23);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(editorTopComponent.class, "editorTopComponent.jLabel3.text")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(48, 152, 48, 14);

        txtRes.setEditable(false);
        txtRes.setColumns(20);
        txtRes.setRows(5);
        jScrollPane1.setViewportView(txtRes);

        add(jScrollPane1);
        jScrollPane1.setBounds(57, 177, 293, 96);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double o1 = Double.parseDouble(op1.getText());
        double o2 = Double.parseDouble(op2.getText());
        
        Collection<? extends Calcula> allFilters = Lookup.getDefault().lookupAll(Calcula.class);
        
        StringBuilder sb = new StringBuilder();
        for (Calcula textFilter : allFilters) {
            String processedText = textFilter.calculo(o1,o2);
            sb.append(processedText).append("\n");
            String str = o1 +", "+o2;
            content.add(str);
            content.add(processedText);
        }
        txtRes.setText(sb.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField op1;
    private javax.swing.JTextField op2;
    private javax.swing.JTextArea txtRes;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
